const countriesMap = {
    "Alaska": "us-ak",
    "Alabama": "us-al",
    "Arkansas": "us-ar",
    "Arizona": "us-az",
    "California": "us-ca",
    "Colorado": "us-co",
    "Connecticut": "us-ct",
    "Delaware": "us-de",
    "Florida": "us-fl",
    "Georgia": "us-ga",
    "Hawaii": "us-hi",
    "Iowa": "us-ia",
    "Idaho": "us-id",
    "Illinois": "us-il",
    "Indiana": "us-in",
    "Kansas": "us-ks",
    "Kentucky": "us-ky",
    "Louisiana": "us-la",
    "Massachusetts": "us-ma",
    "Maryland": "us-md",
    "Maine": "us-me",
    "Michigan": "us-mi",
    "Minnesota": "us-mn",
    "Missouri": "us-mo",
    "Mississippi": "us-ms",
    "Montana": "us-mt",
    "North Carolina": "us-nc",
    "North Dakota": "us-nd",
    "Nebraska": "us-ne",
    "New Hampshire": "us-nh",
    "New Jersey": "us-nj",
    "New Mexico": "us-nm",
    "Nevada": "us-nv",
    "New York": "us-ny",
    "Ohio": "us-oh",
    "Oklahoma": "us-ok",
    "Oregon": "us-or",
    "Pennsylvania": "us-pa",
    "Rhode Island": "us-ri",
    "South Carolina": "us-sc",
    "South Dakota": "us-sd",
    "Tennessee": "us-tn",
    "Texas": "us-tx",
    "Utah": "us-ut",
    "Virginia": "us-va",
    "Vermont": "us-vt",
    "Washington": "us-wa",
    "Wisconsin": "us-wi",
    "West Virginia": "us-wv",
    "Wyoming": "us-wy"
}

export default countriesMap;